//
// Created by Gennadiy Sosnov on 03.10.2022.
//

#ifndef POLYTECH_TITLEBARPROPERTIES_H
#define POLYTECH_TITLEBARPROPERTIES_H

#define BORDER_WIDTH 5
#define TITLE_HEIGHT 28
#define SYS_BUTTONS_HEIGHT 28
#define SYS_BUTTON_WIDTH 46

#endif//POLYTECH_TITLEBARPROPERTIES_H
